/* Question bank. To add more, append rows to RAW: [unit#, question, A, B, C, D, correctIndex(0-3), explanation]
   Units: 0 Jurisprudence, 1 Constitutional & Admin, 2 Public Intl & IHL, 3 Crimes, 4 Torts & Consumer,
   5 Commercial, 6 Family, 7 Environment & Human Rights, 8 IPR & IT, 9 Comparative Public Law.
   Options are shuffled automatically (fixed order for numeric or 'both/neither' options). Verify every answer against standard sources before publishing. */
const UNITS=["Jurisprudence","Constitutional and Administrative Law","Public International Law and IHL","Law of Crimes","Law of Torts and Consumer Protection","Commercial Law","Family Law","Environment and Human Rights Law","Intellectual Property Rights and Information Technology Law","Comparative Public Law and Systems of Governance"];
const RAW=[
// ---- 0 Jurisprudence
[0,"The command theory of law is associated with:","Salmond","Kelsen","John Austin","Savigny",2,"Austin defined law as the command of a sovereign backed by sanction."],
[0,"The Pure Theory of Law was propounded by:","Hans Kelsen","H.L.A. Hart","Roscoe Pound","Jeremy Bentham",0,"Kelsen sought to separate law from morality, politics and sociology."],
[0,"The concept of 'Grundnorm' belongs to:","Austin","Kelsen","Fuller","Dworkin",1,"The Grundnorm is the basic norm that validates all other norms in Kelsen's hierarchy."],
[0,"'The Concept of Law' (1961) was written by:","Lon Fuller","Ronald Dworkin","H.L.A. Hart","Joseph Raz",2,"Hart's work is the leading statement of modern legal positivism."],
[0,"The 'rule of recognition' is a concept of:","Hart","Austin","Pound","Holmes",0,"It is the secondary rule that identifies valid rules of a legal system."],
[0,"Volksgeist (spirit of the people) is central to the school of:","Analytical","Historical","Realist","Natural law",1,"Savigny, the historical school, saw law as growing from the people's spirit."],
[0,"'Law is the prediction of what courts will do' is associated with:","Roscoe Pound","Oliver Wendell Holmes","Austin","Savigny",1,"Holmes expressed this view, which shaped American Legal Realism."],
[0,"'Law as social engineering' is associated with:","Roscoe Pound","Duguit","Kelsen","Maine",0,"Pound's sociological jurisprudence balances competing social interests."],
[0,"In Hohfeld's scheme, the correlative of a claim-right is:","Liberty","Duty","Power","Immunity",1,"If A has a claim-right against B, B owes a duty to A."],
[0,"In Hohfeld's scheme, the correlative of a privilege (liberty) is:","Duty","Liability","No-right","Disability",2,"A liberty to act corresponds to the other party having no-right."],
[0,"Corpus and animus are the two elements of:","Ownership","Possession","Easement","Trust",1,"Possession requires physical control (corpus) and intention to hold (animus)."],
[0,"Which case held that a Hindu idol is a juristic person?","Pramatha Nath Mullick v. Pradyumna Kumar Mullick","Shah Bano","Keshav Singh","Bandhua Mukti Morcha",0,"The Privy Council recognised the idol as a legal person capable of holding property."],
[0,"Thomas Aquinas classified law into eternal, natural, divine and:","Positive law","Human law","Customary law","Moral law",1,"Aquinas's four-fold classification is a key natural law text."],
[0,"'The Morality of Law' and the idea of inner morality of law is associated with:","Lon Fuller","Hart","Kelsen","Bentham",0,"Fuller listed eight principles of legality for a legal system."],
[0,"The Hart–Devlin debate concerned:","Sources of law","Enforcement of morality by law","Judicial review","Legal personality",1,"It followed the Wolfenden Report on homosexuality and prostitution."],
[0,"'A Theory of Justice' (1971) is by:","Amartya Sen","John Rawls","Robert Nozick","Ronald Dworkin",1,"Rawls developed justice as fairness, the original position and the veil of ignorance."],
[0,"Amartya Sen's 'The Idea of Justice' criticises:","Utilitarianism only","Transcendental institutionalism","Legal realism","Historical school",1,"Sen favours a comparative, realisation-focused approach to justice."],
[0,"The maxim 'qui facit per alium facit per se' underlies:","Vicarious liability","Strict liability","Res ipsa loquitur","Estoppel",0,"He who acts through another acts himself, the basis of vicarious liability."],
[0,"Jeremy Bentham is the founder of:","Historical school","Utilitarianism","Natural law","Legal realism",1,"Bentham's principle was the greatest happiness of the greatest number."],
[0,"Salmond defined jurisprudence as the:","Science of first principles of the civil law","Philosophy of positive law only","Study of customs","Study of courts",0,"This is Salmond's classic definition."],
// ---- 1 Constitutional & Administrative
[1,"The Preamble was held to be part of the Constitution in:","Berubari Union case","Kesavananda Bharati","Golaknath","Sajjan Singh",1,"Kesavananda overruled Berubari on this point."],
[1,"Right to education for children aged 6–14 is under:","Article 21A","Article 45","Article 29","Article 30",0,"Inserted by the 86th Amendment, 2002."],
[1,"Fundamental Duties were added by the:","24th Amendment","42nd Amendment","44th Amendment","73rd Amendment",1,"Article 51A was inserted on the Swaran Singh Committee's recommendation."],
[1,"The 'heart and soul' of the Constitution according to Dr. Ambedkar:","Article 14","Article 19","Article 32","Article 226",2,"Article 32 gives the right to move the Supreme Court for fundamental rights."],
[1,"Judicial review of a Presidential Proclamation under Article 356 was affirmed in:","S.R. Bommai v. Union of India","Kihoto Hollohan","Indira Sawhney","L. Chandra Kumar",0,"Bommai (1994) held such a proclamation is justiciable."],
[1,"Procedure for amending the Constitution is in:","Article 356","Article 368","Article 370","Article 352",1,"Article 368 provides Parliament's amending power and procedure."],
[1,"Harmony between Fundamental Rights and DPSPs was held part of the basic structure in:","Minerva Mills","Golaknath","Shankari Prasad","Waman Rao",0,"Minerva Mills (1980) struck down parts of the 42nd Amendment."],
[1,"Articles 14, 19 and 21 are inter-related, and procedure must be fair, just and reasonable, per:","A.K. Gopalan","Maneka Gandhi","ADM Jabalpur","Kharak Singh",1,"Maneka Gandhi (1978) expanded Article 21."],
[1,"The Election Commission of India derives power from:","Article 324","Article 326","Article 329","Article 280",0,"Article 324 vests superintendence of elections in the Commission."],
[1,"Residuary legislative power in India rests with:","States","Union","Concurrent list","Governor",1,"Article 248 and Entry 97 of the Union List give residuary power to Parliament."],
[1,"'Armed rebellion' replaced 'internal disturbance' as ground for National Emergency by:","42nd Amendment","44th Amendment","38th Amendment","52nd Amendment",1,"The 44th Amendment amended Article 352."],
[1,"The rule 'audi alteram partem' means:","No one be a judge in own cause","Hear the other side","Reasoned decision","Legitimate expectation",1,"It is the right to be heard, a core natural justice principle."],
[1,"'Nemo judex in causa sua' is the rule against:","Delay","Bias","Arbitrariness","Retrospectivity",1,"No one should be a judge in their own cause."],
[1,"Which case blurred the distinction between quasi-judicial and administrative functions for natural justice?","A.K. Kraipak v. Union of India","Ridge v. Baldwin","Cooper v. Wandsworth","Maneka Gandhi",0,"Kraipak applied natural justice to administrative action."],
[1,"'Wednesbury unreasonableness' comes from:","Associated Provincial Picture Houses v. Wednesbury Corporation","Ridge v. Baldwin","Entick v. Carrington","Anisminic",0,"A decision so unreasonable that no reasonable authority could make it."],
[1,"Promissory estoppel against the Government was developed in India in:","Motilal Padampat Sugar Mills v. State of U.P.","Kesavananda Bharati","Bachan Singh","Navtej Johar",0,"Motilal Padampat applied the doctrine to public authorities."],
[1,"Lord Diplock's three grounds of judicial review are:","Illegality, irrationality, procedural impropriety","Bias, delay, malice","Jurisdiction, merit, equity","Vires, fairness, necessity",0,"Stated in the GCHQ case (CCSU v. Minister for the Civil Service)."],
[1,"The writ of mandamus means:","We command","You may have the body","By what authority","To be certified",0,"It commands a public authority to perform a public duty."],
[1,"NJAC Act, 2014 was struck down in:","Second Judges Case","Third Judges Case","Supreme Court Advocates-on-Record Association v. Union of India (2015)","S.P. Gupta",2,"The Fourth Judges Case restored the collegium system."],
[1,"The test of 'intelligible differentia' and 'rational nexus' relates to:","Article 14","Article 19","Article 21","Article 25",0,"It is the test for permissible classification under Article 14."],
// ---- 2 Public International Law & IHL
[2,"Customary international law requires state practice and:","Treaty ratification","Opinio juris","Court judgment","UN resolution",1,"Opinio juris is the belief that the practice is legally obligatory."],
[2,"The Vienna Convention on the Law of Treaties was adopted in:","1949","1969","1982","1998",1,"The VCLT was adopted in 1969 and entered into force in 1980."],
[2,"A peremptory norm of general international law is called:","Jus cogens","Erga omnes","Soft law","Pacta sunt servanda",0,"Article 53 VCLT: no derogation allowed."],
[2,"Under the declaratory theory, recognition of a State:","Creates statehood","Merely acknowledges existing statehood","Is a legal duty","Requires UN approval",1,"Statehood exists once the Montevideo criteria are met."],
[2,"The Montevideo Convention (1933) criteria do NOT include:","Defined territory","Permanent population","Effective government","Recognition by the UN Security Council",3,"UN recognition is not a criterion for statehood."],
[2,"The principle of non-refoulement is found in Article 33 of the:","1951 Refugee Convention","Geneva Convention I","UDHR","VCLT",0,"It bars returning refugees to territories where they face persecution."],
[2,"India is:","A party to the 1951 Refugee Convention","Not a party to the 1951 Refugee Convention","A party to its 1967 Protocol only","A party to both",1,"India has not signed either instrument."],
[2,"The 'genuine link' test for nationality was laid down in:","Nottebohm case","Lotus case","Corfu Channel","Asylum case",0,"ICJ, 1955, Liechtenstein v. Guatemala."],
[2,"The rule of double criminality in extradition means:","Offence must be crime in both States","Two trials","Two requests","Two treaties",0,"The act must be an offence in the requesting and requested States."],
[2,"The Asylum case (1950) was between:","Colombia and Peru","Peru and Chile","Argentina and Brazil","Norway and UK",0,"It concerned diplomatic asylum for Haya de la Torre."],
[2,"The number of principal organs of the United Nations is:","Five","Six","Seven","Eight",1,"General Assembly, Security Council, ECOSOC, Trusteeship Council, ICJ, Secretariat."],
[2,"Veto power in the Security Council under Article 27 belongs to:","All members","Five permanent members","Elected members","General Assembly",1,"The P5: China, France, Russia, UK and USA."],
[2,"Enforcement action for threats to the peace is in which Chapter of the UN Charter?","Chapter VI","Chapter VII","Chapter XI","Chapter XIV",1,"Chapter VI covers pacific settlement; Chapter VII covers enforcement."],
[2,"The WTO came into existence in:","1947","1995","2001","1989",1,"WTO replaced the GATT framework from 1 January 1995."],
[2,"The MFN principle under GATT is in:","Article I","Article III","Article XI","Article XX",0,"Most-favoured-nation treatment. National treatment is Article III."],
[2,"How many Geneva Conventions of 1949 exist?","Two","Three","Four","Five",2,"Wounded and sick on land, at sea, prisoners of war, and civilians."],
[2,"The Martens Clause is:","A residual protection for civilians and combatants","A treaty on trade","A rule on extradition","A rule on recognition",0,"It keeps humanity and public conscience as guides where treaty law is silent."],
[2,"The principle of distinction in IHL requires distinguishing between:","Civilians and combatants","Land and sea","States and organisations","Treaty and custom",0,"Attacks may be directed only at military objectives and combatants."],
[2,"The Rome Statute establishing the ICC was adopted in:","1945","1998","2002","1949",1,"Adopted in 1998 and in force from 2002. India is not a party."],
[2,"The Lotus case (1927) held that States may act unless:","Authorised","Prohibited by international law","Approved by UN","Reciprocated",1,"PCIJ: restrictions upon independence of States cannot be presumed."],
// ---- 3 Law of Crimes
[3,"'Actus non facit reum nisi mens sit rea' means:","Act alone does not make guilty unless mind is guilty","Act is crime","Mind is crime","Intention is not needed",0,"Both a guilty act and a guilty mind are generally required."],
[3,"In R v. Prince (1875), the court held:","Knowledge of age was not required","Mens rea was essential","Consent was a defence","Mistake of age excused the accused",0,"Strict interpretation of the statutory offence of abduction."],
[3,"'They also serve who only stand and wait' appears in:","Barendra Kumar Ghosh v. King Emperor","Mahboob Shah","Nanak Chand","Virsa Singh",0,"A leading case on joint liability and common intention."],
[3,"Abetment may be by instigation, conspiracy or:","Intentional aid","Silence","Possession","Omission only",0,"Intentional aiding is the third mode of abetment."],
[3,"Criminal conspiracy requires an agreement between:","Two or more persons","At least five persons","Three persons","Only public servants",0,"Agreement is the essence of the offence."],
[3,"Abhayanand Mishra v. State of Bihar is associated with:","Attempt","Insanity","Provocation","Defamation",0,"The case discusses the stage where preparation becomes attempt."],
[3,"Right of private defence is not available where:","There is time to approach public authorities","Property is attacked","Body is attacked","A woman is attacked",0,"The right does not exist where recourse to authorities is possible."],
[3,"The M'Naghten rules relate to:","Insanity","Intoxication","Necessity","Duress",0,"Laid down in 1843 as the test of insanity."],
[3,"The 'rarest of rare' doctrine for the death penalty comes from:","Bachan Singh v. State of Punjab","Jagmohan Singh","Machhi Singh","Mithu",0,"Bachan Singh (1980) upheld the death penalty in rarest of rare cases."],
[3,"Mandatory death sentence was struck down in:","Mithu v. State of Punjab","Bachan Singh","Rajendra Prasad","Shatrughan Chauhan",0,"Mithu (1983) held a mandatory death sentence unconstitutional."],
[3,"The reformative theory of punishment emphasises:","Rehabilitation of the offender","Revenge","Deterrence of others","Incapacitation",0,"It aims to reform and reintegrate the offender."],
[3,"The Dowry Prohibition Act was enacted in:","1955","1961","1984","1986",1,"The Dowry Prohibition Act, 1961."],
[3,"Under POCSO Act 2012, a 'child' is a person below:","14 years","16 years","18 years","21 years",2,"POCSO defines a child as anyone below eighteen."],
[3,"The principal terror law in India is the:","Unlawful Activities (Prevention) Act, 1967","Arms Act, 1959","NDPS Act, 1985","PMLA, 2002",0,"UAPA was amended to cover terrorist acts."],
[3,"The NDPS Act was enacted in:","1975","1985","1995","2005",1,"Narcotic Drugs and Psychotropic Substances Act, 1985."],
[3,"In 2022 the Supreme Court put the sedition provision in abeyance in:","S.G. Vombatkere v. Union of India","Kedar Nath Singh","Balwant Singh","Shreya Singhal",0,"The Court directed that pending cases be kept in abeyance."],
[3,"The Criminal Law (Amendment) Act, 2013 followed the report of:","Justice Verma Committee","Malimath Committee","Law Commission only","Padmanabhaiah Committee",0,"It followed the Nirbhaya incident of December 2012."],
[3,"Corporate criminal liability was upheld in:","Standard Chartered Bank v. Directorate of Enforcement","Salomon v. Salomon","Vishaka","Shreya Singhal",0,"A company can be prosecuted even where imprisonment is mandatory."],
[3,"An unlawful assembly requires at least:","Three persons","Five persons","Seven persons","Ten persons",1,"Five or more persons with a common unlawful object."],
[3,"A child below what age is conclusively presumed incapable of crime in India?","Five years","Seven years","Ten years","Twelve years",1,"Under both IPC and BNS, a child under seven is exempt."],
// ---- 4 Torts & Consumer
[4,"Strict liability for escape of dangerous things was laid down in:","Rylands v. Fletcher","Donoghue v. Stevenson","Wagon Mound","Bolam",0,"Rylands v. Fletcher (1868)."],
[4,"Absolute liability in India was laid down in:","M.C. Mehta v. Union of India (1987)","Vishaka","Bhopal Gas Leak Act","Municipal Corporation of Delhi v. Subhagwanti",0,"The Oleum gas leak case removed exceptions to strict liability."],
[4,"The neighbour principle was formulated in:","Donoghue v. Stevenson","Rylands v. Fletcher","Bolton v. Stone","Hedley Byrne",0,"Lord Atkin, 1932."],
[4,"The Wagon Mound (No. 1) laid down the test of:","Directness","Reasonable foreseeability of damage","Strict liability","Contributory negligence",1,"Overruled the directness test of Re Polemis."],
[4,"'Volenti non fit injuria' means:","To a willing person no injury is done","Injury without damage","Damage without injury","The thing speaks for itself",0,"Consent is a defence to a tort."],
[4,"Criminal defamation was upheld as constitutional in:","Subramanian Swamy v. Union of India","Shreya Singhal","Puttaswamy","R. Rajagopal",0,"Decided in 2016."],
[4,"Compensation for illegal detention of an MLA was granted in:","Bhim Singh v. State of J&K","Rudul Sah","Nilabati Behera","D.K. Basu",0,"A public-law remedy for violation of Article 21."],
[4,"State liability for non-sovereign functions was recognised in:","State of Rajasthan v. Vidyawati","Kasturilal Ralia Ram Jain","P&O Steam Navigation","Nagendra Rao",0,"Vidyawati (1962) rejected immunity for non-sovereign acts."],
[4,"The doctrine 'res ipsa loquitur' means:","The thing speaks for itself","Let the master answer","Damage without injury","No harm no foul",0,"Negligence may be inferred from the occurrence itself."],
[4,"Private nuisance is interference with:","Use and enjoyment of land","Personal liberty","Reputation","Contract rights",0,"It is an unlawful interference with enjoyment of land."],
[4,"The Consumer Protection Act, 2019 replaced the Act of:","1986","1991","1976","2002",0,"It came into force in July 2020."],
[4,"The authority created under the 2019 Act to regulate unfair trade practices is the:","CCPA","CCI","TRAI","SEBI",0,"Central Consumer Protection Authority."],
[4,"Medical services were held to be 'service' under consumer law in:","Indian Medical Association v. V.P. Shantha","Jacob Mathew","Bolam","Samira Kohli",0,"Decided in 1995."],
[4,"For criminal medical negligence, the standard is:","Gross negligence","Slight negligence","Strict liability","Absolute liability",0,"Jacob Mathew v. State of Punjab (2005)."],
[4,"No-fault liability under the Motor Vehicles Act means compensation:","Irrespective of fault","Only on proof of negligence","Only to drivers","Only for property",0,"Statutory fixed compensation without proving fault."],
[4,"The Competition Act, 2002 replaced the:","MRTP Act, 1969","FERA","Companies Act 1956","SEBI Act",0,"It created the Competition Commission of India."],
[4,"Contributory negligence results in:","Reduced damages","No liability","Higher damages","Punitive damages",0,"Claimant's own fault reduces recovery."],
[4,"'Damnum sine injuria' means:","Damage without legal injury","Legal injury without damage","Damage with injury","Injury to property",0,"Illustrated by Gloucester Grammar School case."],
[4,"'Injuria sine damno' was illustrated in:","Ashby v. White","Bradford v. Pickles","Mogul Steamship","Donoghue",0,"Violation of a legal right is actionable even without loss."],
[4,"Employer's liability for an employee's tort in course of employment is:","Vicarious liability","Absolute liability","Strict liability","Contributory liability",0,"Rooted in respondeat superior."],
// ---- 5 Commercial
[5,"The Indian Contract Act was enacted in:","1872","1882","1930","1932",0,"Indian Contract Act, 1872."],
[5,"General offer to the world was upheld in:","Carlill v. Carbolic Smoke Ball Co.","Balfour v. Balfour","Hadley v. Baxendale","Taylor v. Caldwell",0,"An offer to the public can be accepted by performing the condition."],
[5,"A minor's agreement is void ab initio per:","Mohori Bibee v. Dharmodas Ghose","Carlill","Hyde v. Wrench","Felthouse v. Bindley",0,"Privy Council, 1903."],
[5,"The remoteness rule in contract damages comes from:","Hadley v. Baxendale","Wagon Mound","Donoghue","Salomon",0,"Reflected in Section 73 of the Contract Act."],
[5,"Doctrine of frustration/impossibility in India is under:","Section 56","Section 10","Section 73","Section 124",0,"Satyabrata Ghose v. Mugneeram Bangur explains it."],
[5,"Quasi-contract rests on the principle of:","Unjust enrichment","Free consent","Estoppel","Indemnity",0,"A person should not unjustly enrich themselves at another's expense."],
[5,"Unconscionable standard-form contracts were considered in:","Central Inland Water Transport v. Brojo Nath Ganguly","Mohori Bibee","Carlill","Bhagwandas Goverdhandas Kedia",0,"The Court struck down an unfair clause."],
[5,"A contract of guarantee involves how many parties?","Two","Three","Four","Five",1,"Surety, principal debtor and creditor."],
[5,"Pledge is a bailment for:","Security for debt or promise","Gratuitous carriage","Hire","Sale",0,"Goods are bailed as security."],
[5,"An agent's relationship to the principal is:","Fiduciary","Contractual only","Adverse","Customary",0,"An agent owes duties of loyalty and disclosure."],
[5,"The Sale of Goods Act was enacted in:","1930","1872","1881","1932",0,"Sale of Goods Act, 1930."],
[5,"Breach of a condition in sale entitles the buyer to:","Repudiate the contract","Only damages","Only specific performance","Nothing",0,"Breach of warranty gives only damages."],
[5,"A limited liability partnership is governed by the:","LLP Act, 2008","Partnership Act, 1932","Companies Act, 2013","Contract Act",0,"An LLP is a separate legal entity."],
[5,"Dishonour of a cheque for insufficient funds is an offence under Section:","138 NI Act","420 IPC","73 Contract Act","27 Companies Act",0,"Section 138, Negotiable Instruments Act, 1881."],
[5,"Separate legal personality of a company was established in:","Salomon v. Salomon & Co.","Foss v. Harbottle","Ashbury","Lee v. Lee's Air Farming",0,"House of Lords, 1897."],
[5,"The rule of majority rule and proper plaintiff comes from:","Foss v. Harbottle","Salomon","Macaura","Daimler",0,"Courts do not interfere in internal management where the majority can ratify."],
[5,"Under Section 135 Companies Act, CSR spend is of average net profits of preceding three years:","1%","2%","3%","5%",1,"Two per cent for companies meeting thresholds."],
[5,"A prospectus is an invitation to:","The public to subscribe to securities","Existing shareholders only","Banks","Courts",0,"A document inviting offers from the public."],
[5,"The doctrine of ultra vires in company law is illustrated by:","Ashbury Railway Carriage v. Riche","Salomon","Foss v. Harbottle","Royal British Bank v. Turquand",0,"Acts beyond the objects clause are void."],
[5,"Validity of contracts formed electronically is recognised under:","Section 10A, IT Act, 2000","Section 10, Contract Act","Section 65B Evidence Act","Section 43 IT Act",0,"Section 10A IT Act."],
// ---- 6 Family Law
[6,"The Hindu Marriage Act was enacted in:","1955","1956","1954","1961",0,"Hindu Marriage Act, 1955."],
[6,"Instant triple talaq was held invalid in:","Shayara Bano v. Union of India","Shah Bano","Danial Latifi","Mohd. Ahmed Khan",0,"Decided in 2017."],
[6,"The Muslim Women (Protection of Rights on Marriage) Act, 2019 criminalised:","Instant triple talaq","Polygamy","Nikah halala","Mehr",0,"Talaq-e-biddat is void and punishable."],
[6,"Maintenance to a divorced Muslim woman under Section 125 CrPC was upheld in:","Shah Bano","Shayara Bano","Sarla Mudgal","Vineeta Sharma",0,"Mohd. Ahmed Khan v. Shah Bano Begum (1985)."],
[6,"Mahr (dower) belongs to:","Muslim law","Hindu law","Christian law","Parsi law",0,"A sum payable by the husband to the wife on marriage."],
[6,"Stridhan was considered in:","Pratibha Rani v. Suraj Kumar","Shah Bano","Kesavananda","Vishaka",0,"The wife has absolute rights over her stridhan."],
[6,"Daughters became coparceners by birth by the Hindu Succession (Amendment) Act of:","1991","2005","2015","1956",1,"Vineeta Sharma v. Rakesh Sharma (2020) clarified it applies irrespective of father's death date."],
[6,"Adoption available to persons of any religion is under the:","Juvenile Justice Act, 2015","HAMA 1956","Special Marriage Act","Guardians and Wards Act",0,"Shabnam Hashmi v. Union of India (2014)."],
[6,"A mother was recognised as natural guardian during father's lifetime in:","Gita Hariharan v. RBI","Vishaka","Shah Bano","Danial Latifi",0,"Decided in 1999."],
[6,"The Special Marriage Act was enacted in:","1954","1955","1872","1936",0,"It provides civil marriage irrespective of religion."],
[6,"'Relationship in the nature of marriage' appears in:","Protection of Women from Domestic Violence Act, 2005","Hindu Marriage Act","Special Marriage Act","Muslim Personal Law Act",0,"Live-in relationships are covered."],
[6,"Recognition of foreign matrimonial decrees was considered in:","Y. Narasimha Rao v. Y. Venkata Lakshmi","Sarla Mudgal","Shah Bano","Danial Latifi",0,"Section 13 CPC governs."],
[6,"The Uniform Civil Code is mentioned in:","Article 44","Article 25","Article 21","Article 51A",0,"A Directive Principle."],
[6,"A Muslim can bequeath by will without heirs' consent up to:","One-third","One-half","Two-thirds","Entire estate",0,"Beyond one-third requires consent."],
[6,"Essentials of hiba (gift) in Muslim law include declaration, acceptance and:","Delivery of possession","Registration","Consideration","Witnesses",0,"Delivery of possession completes the gift."],
[6,"Birth right by birth in the joint family in father's lifetime belongs to:","Mitakshara","Dayabhaga","Both","Neither",0,"Dayabhaga gives no right by birth during father's life."],
[6,"Restitution of conjugal rights was upheld in:","Saroj Rani v. Sudarshan Kumar","Sareetha v. Venkata Subbaiah","Shayara Bano","Hirachand Srinivas",0,"The Supreme Court upheld Section 9 HMA."],
[6,"The Supreme Court held a divorced Muslim woman can claim maintenance under Section 125 CrPC in:","Mohd. Abdul Samad v. State of Telangana","Danial Latifi","Shabnam Hashmi","Rajesh Sharma",0,"Decided in 2024."],
[6,"Minimum marriage age for a woman in India under PCMA 2006 is:","16","18","21","15",1,"Eighteen for women, twenty-one for men."],
[6,"The Parsi Marriage and Divorce Act was enacted in:","1936","1955","1869","1872",0,"Parsi Marriage and Divorce Act, 1936."],
// ---- 7 Environment & Human Rights
[7,"The Stockholm Declaration was adopted in:","1972","1992","2002","1987",0,"UN Conference on the Human Environment, 1972."],
[7,"The precautionary principle is stated in Rio Declaration Principle:","15","10","1","21",0,"Adopted at the 1992 Earth Summit."],
[7,"The polluter pays principle was applied in:","Indian Council for Enviro-Legal Action v. Union of India","Shah Bano","Kesavananda","Vishaka",0,"Decided in 1996."],
[7,"The Vellore Citizens' Welfare Forum case adopted:","Precautionary principle and sustainable development","Only strict liability","Public trust only","None",0,"Decided in 1996."],
[7,"Public trust doctrine in India was applied in:","M.C. Mehta v. Kamal Nath","Shah Bano","Maneka Gandhi","Vishaka",0,"Decided in 1997."],
[7,"Duty to protect the environment as a fundamental duty is in:","Article 51A(g)","Article 48A","Article 21","Article 14",0,"Article 48A is a Directive Principle."],
[7,"The Environment (Protection) Act was passed in:","1986","1974","1981","2010",0,"It followed the Bhopal Gas tragedy."],
[7,"The National Green Tribunal was established in:","2010","2002","1986","2015",0,"National Green Tribunal Act, 2010."],
[7,"The EIA Notification currently followed was issued under EPA in:","2006","1994","2011","2020 only",0,"EIA Notification, 2006."],
[7,"The Basel Convention relates to:","Transboundary movement of hazardous wastes","Ozone layer","Climate change","Biodiversity",0,"Adopted in 1989."],
[7,"The Montreal Protocol concerns:","Ozone-depleting substances","Greenhouse gases","Wetlands","Whaling",0,"Adopted in 1987."],
[7,"The Paris Agreement was adopted in:","2015","1997","2009","2022",0,"Adopted at COP21."],
[7,"Right to a pollution-free environment under Article 21 was held in:","Subhash Kumar v. State of Bihar","Shah Bano","Kesavananda","ADM Jabalpur",0,"Decided in 1991."],
[7,"'Our Common Future' (1987) is the report of the:","Brundtland Commission","Club of Rome","Rio Conference","Kyoto Conference",0,"It popularised sustainable development."],
[7,"The UDHR was adopted on:","10 December 1948","26 January 1950","24 October 1945","16 December 1966",0,"Celebrated as Human Rights Day."],
[7,"The International Bill of Human Rights comprises UDHR, ICCPR and:","ICESCR","CEDAW","CRC","CAT",0,"Adopted in 1966, in force 1976."],
[7,"Cultural relativism holds that human rights are:","Culture-dependent","Universal","Absolute","Natural only",0,"It contrasts with universalism."],
[7,"The Protection of Human Rights Act was passed in:","1993","1986","2005","2013",0,"It created the NHRC."],
[7,"The Rights of Persons with Disabilities Act, 2016 recognises how many disabilities?","7","14","21","25",2,"It replaced the 1995 Act."],
[7,"Sexual harassment guidelines at workplace were laid down in:","Vishaka v. State of Rajasthan","Shah Bano","Maneka Gandhi","Nilabati Behera",0,"1997, later followed by POSH Act 2013."],
// ---- 8 IPR & IT
[8,"The Berne Convention relates to:","Copyright","Patents","Trademarks","Designs",0,"Adopted in 1886."],
[8,"The TRIPS Agreement is administered by the:","WTO","WIPO","UNESCO","UNCTAD",0,"It sets minimum standards for IP protection."],
[8,"The Paris Convention (1883) concerns:","Industrial property","Copyright","Performers","Broadcasting",0,"Patents, marks and designs."],
[8,"Copyright in literary works in India lasts for author's life plus:","50 years","60 years","70 years","25 years",1,"Sixty years from the year after death."],
[8,"Idea-expression dichotomy was applied in India in:","R.G. Anand v. Delux Films","Novartis","Bayer","Shreya Singhal",0,"Decided in 1978."],
[8,"Moral rights of authors are under:","Section 57, Copyright Act","Section 52","Section 14","Section 63",0,"Rights of paternity and integrity."],
[8,"The Patents Act was enacted in:","1970","1957","1999","2000",0,"Patents Act, 1970."],
[8,"Term of a patent in India is:","20 years from filing","14 years","25 years","10 years",0,"Twenty years from the date of filing."],
[8,"Evergreening and Section 3(d) were considered in:","Novartis AG v. Union of India","Bayer v. Natco","Roche v. Cipla","Monsanto v. Nuziveedu",0,"Decided in 2013."],
[8,"India's first compulsory licence was granted in:","Natco Pharma v. Bayer","Novartis","Roche","Pfizer",0,"Concerned Nexavar, 2012."],
[8,"The Trade Marks Act was enacted in:","1999","1957","1970","2000",0,"Trade Marks Act, 1999."],
[8,"Initial registration of a trademark lasts:","10 years","7 years","5 years","20 years",0,"Renewable for ten-year periods."],
[8,"Passing off protects:","Goodwill","Patents","Copyright","Designs",0,"A common-law remedy."],
[8,"Deceptive similarity was considered in:","Amritdhara Pharmacy v. Satya Deo Gupta","Novartis","R.G. Anand","Shreya Singhal",0,"Decided in 1963."],
[8,"The first Indian GI tag was granted to:","Darjeeling Tea","Basmati","Pochampally","Kancheepuram Silk",0,"GI Act, 1999."],
[8,"The Biological Diversity Act was enacted in:","2002","1992","2010","1986",0,"It created the NBA."],
[8,"Section 66A of the IT Act was struck down in:","Shreya Singhal v. Union of India","Puttaswamy","Anuradha Bhasin","Faheema Shirin",0,"Decided in 2015."],
[8,"The IT Act, 2000 is modelled on the:","UNCITRAL Model Law on E-Commerce","TRIPS","Berne","Budapest Convention",0,"Adopted by UNCITRAL in 1996."],
[8,"Right to privacy as a fundamental right was held in:","K.S. Puttaswamy v. Union of India","Kharak Singh","M.P. Sharma","Gobind",0,"Decided in 2017."],
[8,"The Digital Personal Data Protection Act was enacted in:","2023","2019","2000","2021",0,"Received assent in August 2023."],
// ---- 9 Comparative Public Law
[9,"The first modern federation is considered to be:","USA","Canada","Switzerland","India",0,"The US Constitution, 1787."],
[9,"Residuary powers in Canada rest with:","Federal Parliament","Provinces","Courts","Governor General",0,"A strong-centre federation."],
[9,"Montesquieu's 'Spirit of the Laws' propounded:","Separation of powers","Rule of law","Judicial review","Federalism",0,"Published in 1748."],
[9,"In a parliamentary system the executive is responsible to:","Legislature","Judiciary","Voters directly","President",0,"Collective responsibility to the House."],
[9,"Dicey's three meanings of the rule of law include:","Supremacy of regular law","Natural rights","Executive discretion","Administrative courts",0,"Also equality before law and constitution as result of ordinary law."],
[9,"The formal version of the rule of law is associated with:","Joseph Raz","Dworkin","Fuller only","Rawls",0,"Raz: The Rule of Law and Its Virtue."],
[9,"Judicial review in the USA began with:","Marbury v. Madison","McCulloch v. Maryland","Brown v. Board","Dred Scott",0,"Decided in 1803."],
[9,"France's Conseil constitutionnel conducts:","Pre-promulgation review","Only post-enactment review","No review","Review by Senate",0,"A priori abstract review."],
[9,"A US constitutional amendment needs ratification by:","Three-fourths of States","Two-thirds of States","Half of States","Governors",0,"After proposal by two-thirds of Congress."],
[9,"The institution of Ombudsman originated in:","Sweden","UK","India","USA",0,"1809."],
[9,"UK's Parliamentary Commissioner for Administration was created in:","1967","1809","1950","2005",0,"Parliamentary Commissioner Act, 1967."],
[9,"India's Lokpal and Lokayuktas Act was enacted in:","2013","2005","2011","1993",0,"Received assent in 2014 and came in force."],
[9,"India's RTI Act was enacted in:","2005","2000","2013","1972",0,"Right to Information Act, 2005."],
[9,"US Freedom of Information Act was enacted in:","1966","1946","1974","2005",0,"FOIA, 1966."],
[9,"The UK Supreme Court was established under the:","Constitutional Reform Act, 2005","HRA 1998","Magna Carta","Act of Settlement",0,"It began work in 2009."],
[9,"PIL jurisprudence was pioneered in India by Justices:","P.N. Bhagwati and V.R. Krishna Iyer","H.R. Khanna and Beg","Chandrachud and Reddy","Sikri and Hegde",0,"S.P. Gupta (1981) widened locus standi."],
[9,"The functional method is associated with comparative law scholars:","Zweigert and Kötz","Austin and Hart","Kelsen and Pound","Dicey and Bagehot",0,"They emphasise comparing legal solutions to common problems."],
[9,"Germany's 'eternity clause' is in:","Article 79(3) Basic Law","Article 1","Article 20","Article 93",0,"It bars amendments affecting basic principles."],
[9,"Parliamentary sovereignty is a feature of the:","UK","USA","Switzerland","South Africa",0,"Dicey's central principle."],
[9,"Federalism was held part of India's basic structure in:","S.R. Bommai v. Union of India","Golaknath","Berubari","Kihoto Hollohan",0,"1994."]
];
const QBANK=[
 {u:UNITS[1],q:"Which case is most closely associated with the Basic Structure Doctrine in India?",o:["A. A.K. Gopalan v State of Madras","B. Kesavananda Bharati v State of Kerala","C. Maneka Gandhi v Union of India","D. S.R. Bommai v Union of India"],a:1,e:"The Supreme Court's 1973 decision in Kesavananda Bharati is the leading authority for the Basic Structure Doctrine."},
 ...RAW.map((r,n)=>{let o=r.slice(2,6),a=r[6];
  const fixed=o.some(t=>/^(both|neither|none|all of)/i.test(t))||o.filter(t=>/^(\d|one|two|three|four|five|six|seven|eight|nine|ten)\b/i.test(t)).length>=3;
  if(!fixed){let x=n*9973+7;const rnd=()=>(x=(x*1664525+1013904223)>>>0)/4294967296,c=o[a];
   for(let i=3;i>0;i--){const j=Math.floor(rnd()*(i+1));[o[i],o[j]]=[o[j],o[i]]}a=o.indexOf(c)}
  return{u:UNITS[r[0]],q:r[1],o:o.map((t,i)=>"ABCD"[i]+". "+t),a,e:r[7]}})
];
