const questions=[
 {q:"Which case is most closely associated with the Basic Structure Doctrine in India?",o:["A. A.K. Gopalan v State of Madras","B. Kesavananda Bharati v State of Kerala","C. Maneka Gandhi v Union of India","D. S.R. Bommai v Union of India"],a:1,e:"The Supreme Court's 1973 decision in Kesavananda Bharati is the leading authority for the Basic Structure Doctrine."},
 {q:"The idea–expression dichotomy principally means that copyright protects:",o:["A. Ideas in the abstract","B. Facts alone","C. Expression of ideas, subject to the requirements of copyright law","D. Every original thought"],a:2,e:"Copyright generally protects original expression rather than ideas, concepts or themes in the abstract."},
 {q:"Which of the following is a recognised source of international law under Article 38(1) of the ICJ Statute?",o:["A. Judicial decisions only","B. International conventions","C. Domestic legislation of one State","D. Political speeches"],a:1,e:"Article 38(1) lists international conventions, international custom, and general principles of law, with judicial decisions and teachings as subsidiary means."},
 {q:"In contract law, consideration is generally understood as:",o:["A. A moral obligation only","B. Something of value exchanged in support of a promise","C. A court judgment","D. A statutory penalty"],a:1,e:"Consideration is the value or legal detriment/benefit exchanged in relation to a promise, subject to the applicable statutory rules."},
 {q:"Which institution is the constitutional court of India?",o:["A. High Court","B. District Court","C. Supreme Court","D. Tribunal"],a:2,e:"The Supreme Court is India's apex constitutional court and exercises constitutional jurisdiction including judicial review."}
];
let current=0,score=0,answered=false;
const qEl=document.getElementById("question"), optEl=document.getElementById("options"), expEl=document.getElementById("explanation"), next=document.getElementById("next"), restart=document.getElementById("restart"), num=document.getElementById("q-number"), scoreEl=document.getElementById("score"), bar=document.getElementById("quiz-bar");
function render(){answered=false;next.disabled=true;expEl.classList.add("hidden");const x=questions[current];qEl.textContent=x.q;num.textContent=`Question ${current+1} of ${questions.length}`;scoreEl.textContent=`Score: ${score}`;bar.style.width=((current)/questions.length*100)+"%";optEl.innerHTML="";x.o.forEach((t,i)=>{const b=document.createElement("button");b.className="option";b.textContent=t;b.onclick=()=>answer(i);optEl.appendChild(b)})}
function answer(i){if(answered)return;answered=true;const x=questions[current];document.querySelectorAll(".option").forEach((b,n)=>{b.disabled=true;if(n===x.a)b.classList.add("correct");if(n===i&&n!==x.a)b.classList.add("wrong")});if(i===x.a)score++;scoreEl.textContent=`Score: ${score}`;expEl.innerHTML=`<strong>Explanation:</strong> ${x.e}`;expEl.classList.remove("hidden");next.disabled=false;bar.style.width=((current+1)/questions.length*100)+"%";next.textContent=current===questions.length-1?"See Result →":"Next Question →"}
next.onclick=()=>{if(current<questions.length-1){current++;render()}else{qEl.textContent=`Quiz complete — ${score}/${questions.length}`;optEl.innerHTML="";expEl.innerHTML=score>=4?"Strong start. Keep practising.":"Good practice. Review the explanations and try again.";expEl.classList.remove("hidden");next.disabled=true;next.textContent="Completed";}};
restart.onclick=()=>{current=0;score=0;render()};
render();
document.querySelector(".menu-toggle").onclick=()=>document.getElementById("main-nav").classList.toggle("open");
