const syllabus = {
 paper1: [
  ["Teaching Aptitude",["Teaching: concept, objectives, levels (memory, understanding and reflective) and characteristics","Learner characteristics: adolescent and adult learners; individual differences","Factors affecting teaching: teacher, learner, support material, facilities, environment and institution","Methods of teaching in institutions of higher learning: teacher-centred and learner-centred; offline and online","Teaching support systems: traditional, modern and ICT-based","Evaluation systems: elements and types of evaluation; CBCS; computer-based testing; innovations" ]],
  ["Research Aptitude",["Research: meaning, types, characteristics and approaches","Research methods: experimental, descriptive, historical, qualitative and quantitative","Steps of research","Thesis and article writing: format and styles of referencing","Application of ICT in research","Research ethics: integrity, plagiarism and responsible conduct" ]],
  ["Comprehension",["Reading comprehension of a passage","Identification of central theme, arguments and supporting ideas","Inference, implication and logical conclusions","Meaning of words and expressions in context" ]],
  ["Communication",["Communication: meaning, types and characteristics","Effective communication: verbal, non-verbal, intercultural and group communication","Classroom communication and barriers to effective communication","Mass media and society" ]],
  ["Mathematical Reasoning and Aptitude",["Types of reasoning","Number series, letter series, codes and relationships","Basic mathematical aptitude: fractions, time and distance, ratio, proportion and percentage","Profit and loss, interest, averages, discounts and simple calculations" ]],
  ["Logical Reasoning",["Understanding the structure of arguments: argument forms, structure and fallacies","Categorical propositions, mood and figure; formal and informal fallacies","Uses of language, connotations and denotations; classical square of opposition","Evaluating and distinguishing deductive and inductive reasoning","Analogies","Venn diagrams: simple and multiple uses for establishing validity","Indian logic: means of knowledge; pramanas; inference and structure of inference" ]],
  ["Data Interpretation",["Sources, acquisition and classification of data","Quantitative and qualitative data","Data representation: tables, bar charts, histograms, pie charts and line charts","Mapping of data","Data interpretation and analysis","Data and governance" ]],
  ["Information and Communication Technology (ICT)",["ICT: general abbreviations and terminology","Basics of internet, intranet, e-mail and audio/video conferencing","Digital initiatives in higher education","ICT and governance" ]],
  ["People, Development and Environment",["Development and environment: millennium and sustainable development goals","Human-environment interaction; anthropogenic activities and environmental impact","Environmental issues: local, regional and global; air, water, soil, noise and waste pollution","Climate change, global warming, ozone depletion, acid rain and impacts on human health","Natural and energy resources: solar, wind, soil, hydro, geothermal, biomass and nuclear","Natural hazards and disasters; mitigation and management","Environmental protection legislation and international agreements","Environmental assessment and education" ]],
  ["Higher Education System",["Institutions of higher learning and education in ancient India","Evolution of higher learning and research in post-independence India","Oriental, conventional and non-conventional learning programmes","Professional, technical and skill-based education","Value education and environmental education","Policies, governance and administration: structure of higher education and regulatory bodies" ]]
 ],
 law: [
  ["Jurisprudence",["Nature and sources of law","Schools of jurisprudence","Law and morality","Concept of rights and duties","Legal personality","Concepts of property, ownership and possession","Concept of liability","Law, poverty and development","Global justice","Modernism and post-modernism"]],
  ["Constitutional and Administrative Law",["Preamble, fundamental rights and duties, directive principles of state policy","Union and State executive and their interrelationship","Union and State legislature and distribution of legislative powers","Judiciary","Emergency provisions","Temporary, transitional and special provisions in respect of certain states","Election Commission of India","Nature, scope and importance of administrative law","Principle of natural justice","Judicial review of administrative actions – grounds"]],
  ["Public International Law and IHL",["International law: definition, nature and basis","Sources of international law","Recognition of states and governments","Nationality, immigrants, refugees and internally displaced persons (IDPs)","Extradition and asylum","United Nations and its organs","Settlement of international disputes","World Trade Organization (WTO)","International humanitarian law: conventions and protocols","Implementation of IHL: challenges"]],
  ["Law of Crimes",["General principles of criminal liability: actus reus and mens rea; individual, group and constructive liability","Stages of crime and inchoate crimes: abetment, criminal conspiracy and attempt","General exceptions","Offences against human body","Offences against State and terrorism","Offences against property","Offences against women and children","Drug trafficking and counterfeiting","Offences against public tranquillity","Theories and kinds of punishments; compensation to victims of crime"]],
  ["Law of Torts and Consumer Protection",["Nature and definition of tort","General principles of tortious liability","General defences","Specific torts: negligence, nuisance, trespass and defamation","Remoteness of damages","Strict and absolute liability","Tortious liability of the State","Consumer Protection Act, 1986: definitions, consumer rights and redressal mechanism (study alongside the current 2019 Act and amendments)","Motor Vehicles Act, 1988: no-fault liability, third-party insurance and claims tribunal","Competition Act, 2002: prohibited agreements, abuse of dominance and regulation of combinations"]],
  ["Commercial Law",["Essential elements of contract and e-contract","Breach of contract, frustration, void and voidable agreements","Standard-form contracts and quasi-contract","Specific contracts: bailment, pledge, indemnity, guarantee and agency","Sale of Goods Act, 1930","Partnership and limited liability partnership","Negotiable Instruments Act, 1881","Company law: incorporation, prospectus, shares and debentures","Company law: directors and meetings","Corporate social responsibility"]],
  ["Family Law",["Sources and schools","Marriage and dissolution of marriage","Matrimonial remedies: divorce and theories of divorce","Changing dimensions of marriage: live-in relationship","Recognition in India of foreign decrees on marriage and divorce","Maintenance, dower and stridhan","Adoption, guardianship and acknowledgement","Succession and inheritance","Will, gift and wakf","Uniform Civil Code"]],
  ["Environment and Human Rights Law",["Meaning and concept of environment and environmental pollution","International environmental law and UN conferences","Constitutional and legal framework for environmental protection in India","Environmental Impact Assessment and control of hazardous waste in India","National Green Tribunal","Concept and development of human rights","Universalism and cultural relativism","International Bill of Rights","Group rights: women, children, persons with disabilities, elderly persons, minorities and weaker sections","Protection and enforcement of human rights in India: NHRC and national commissions"]],
  ["Intellectual Property Rights and Information Technology Law",["Concept and meaning of intellectual property","Theories of intellectual property","International conventions pertaining to intellectual property","Copyright and neighbouring rights: subject matter, limitations, exceptions, infringement and remedies","Patent law: patentability, grant procedure, limitations, exceptions, infringement and remedies","Trademark law: registration, kinds, infringement, passing off and remedies","Protection of geographical indications","Biodiversity and traditional knowledge","Information technology law: digital and electronic signatures, e-governance, electronic records and subscriber duties","Cybercrimes, penalties and adjudication"]],
  ["Comparative Public Law and Systems of Governance",["Comparative law: relevance, methodology, problems and concerns","Forms of government: presidential and parliamentary; unitary and federal","Models of federalism: USA, Canada and India","Rule of law: formal and substantive versions","Separation of powers: India, UK, USA and France","Judicial independence, activism and accountability: India, UK and USA","Systems of constitutional review: India, USA, Switzerland and France","Constitutional amendment: India, USA and South Africa","Ombudsman: Sweden, UK and India","Open government and right to information: USA, UK and India"]]
 ]
};
